template: true
valuesFilePath: ./values.yml

resources:
  - name: {{ .Values.gitRepo.name }}
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitRepo.provider }}
      path: {{ .Values.gitRepo.path }}
      # branches:
      #   include: {{ .Values.myRepo.branch }}

  - name: "{{ .Values.pipelines.name }}_chart"
    type: HelmChart
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}
      repository: {{ .Values.artifactoryRepo.target.name }}
      chart: {{ .Values.helm.chart.name }}
      version: {{ .Values.helm.chart.version }}
      
pipelines:
  - name: {{ .Values.pipelines.name }}
    steps:
      - name: helm_publish
        type: HelmPublish
        configuration:          
          inputResources:
            - name: {{ .Values.gitRepo.name }}
          outputResources:
            - name: "{{ .Values.pipelines.name }}_chart"
          chartPath: {{ .Values.helm.chart.path }}
        # execution:
        #   onStart:
        #     - echo "[TM] manually login to artifactory"
        #     - echo ${int_{{ .Values.artifactory }}_apikey} | docker login --username {{ .Values.artifactoryRepo.username }} --password-stdin ${int_{{ .Values.artifactory }}_url}
