replicaCount: 3
image:
  repository: ${res_sample_docker__sample_hello_app_imageName}
  tag: ${res_sample_docker__sample_hello_app_imageTag}
  pullPolicy: IfNotPresent
  port: 8080
  pullSecret: regcred
service:
  type: ClusterIP  
  port: 80
ingress:
  host: hello-app.app.tsuyo.org